# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

DECIDIM_VERSION = "~> 0.27.0"

gem "decidim", DECIDIM_VERSION
gem "decidim-admin", DECIDIM_VERSION
gem "decidim-core", DECIDIM_VERSION
gem "decidim-gallery", path: ".."

gem "activerecord", "~> 6.1"
gem "activesupport", "~> 6.1"
gem "rails", "~> 6.1.0"

gem "bootsnap", "~> 1.4"
gem "faker", "~> 2.14"
gem "rspec", "~> 3.13"

group :development, :test do
  gem "brakeman", "~> 5.1"
  gem "byebug", "~> 11.0", platform: :mri
  gem "climate_control", "~> 1.2"
  gem "decidim-dev", DECIDIM_VERSION
  gem "parallel_tests"
end

group :development do
  gem "letter_opener_web", "~> 1.3"
  gem "listen", "~> 3.1"
  gem "rubocop-faker"
  gem "spring", "~> 2.0"
  gem "spring-watcher-listen", "~> 2.0"
  gem "web-console", "~> 4.1"
end

group :test do
  gem "codecov", require: false
end
